/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsVoltRouteImport } from './routes/products/volt'
import { Route as ProductsVibesRouteImport } from './routes/products/vibes'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsVoltRoute = ProductsVoltRouteImport.update({
  id: '/products/volt',
  path: '/products/volt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsVibesRoute = ProductsVibesRouteImport.update({
  id: '/products/vibes',
  path: '/products/vibes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/products/vibes': typeof ProductsVibesRoute
  '/products/volt': typeof ProductsVoltRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/products/vibes': typeof ProductsVibesRoute
  '/products/volt': typeof ProductsVoltRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/products/vibes': typeof ProductsVibesRoute
  '/products/volt': typeof ProductsVoltRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/contact'
    | '/services'
    | '/products/vibes'
    | '/products/volt'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/contact'
    | '/services'
    | '/products/vibes'
    | '/products/volt'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/contact'
    | '/services'
    | '/products/vibes'
    | '/products/volt'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  ProductsVibesRoute: typeof ProductsVibesRoute
  ProductsVoltRoute: typeof ProductsVoltRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/volt': {
      id: '/products/volt'
      path: '/products/volt'
      fullPath: '/products/volt'
      preLoaderRoute: typeof ProductsVoltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/vibes': {
      id: '/products/vibes'
      path: '/products/vibes'
      fullPath: '/products/vibes'
      preLoaderRoute: typeof ProductsVibesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  ProductsVibesRoute: ProductsVibesRoute,
  ProductsVoltRoute: ProductsVoltRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
